language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-19mode

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_master.gemfile

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - gemfile: gemfiles/rails_master.gemfile

notifications:
  email: false
